### ISSUE TITLE
booki1 training

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/new-ui-designer-training#11]
Complete #1, Share your deliverables as comments below unless otherwise stated

**Comment by booki1** [comment]
https://www.figma.com/file/8tj51cPx9VEALUOokgtBA5/uwu?node-id=0%3A1
Wasn't sure of how to share account? Email is carolwang2003@gmail.com

**Comment by WilliamShih1234** [comment]
On Figma, you can click the top right blue button that says "Share", and then click copy link on the box that appears. Paste the link as a comment here, that way we will have access to your finished training project.

**Comment by booki1** [comment]
https://www.figma.com/file/8tj51cPx9VEALUOokgtBA5/uwu?node-id=0%3A1

**Comment by WilliamShih1234** [comment]
Nice. move on to #2

**Comment by booki1** [comment]
https://www.figma.com/file/4fzi77mGygLMU8JlF8RVNE/Practice-2?node-id=0%3A1

**Comment by WilliamShih1234** [comment]
Looks great! This will be your last training before you are ready to start designing parts of websites for our projects! Complete #3 and post it!

**Comment by booki1** [comment]
https://www.figma.com/file/llURREldNLEc9jkXwBFOWs/Training-3?node-id=0%3A1

**Comment by WilliamShih1234** [comment]
Looks good, go ahead and assign yourself some tasks that are posted on the Slack chat ui_design!
