### ISSUE TITLE
whichlee training

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/new-ui-designer-training#12]
Complete #1, Share your deliverables as comments below unless otherwise stated

**Comment by whichlee** [comment]
First design test following the tutorial:
https://www.figma.com/file/bZRR9oVTMv3q8hqVk2zDmI/tutorial?node-id=0%3A1

**Comment by whichlee** [comment]
I'm not entirely sure how to send you my figma account, but I am using my tasha_j_lee@yahoo.com email and the name is "Natasha". The profile picture is also the same as here

**Comment by WilliamShih1234** [comment]
You shared it right. move on to #2

**Comment by whichlee** [comment]
https://www.figma.com/file/gBoZNMJ3E1NxUig9nM3s3X/tutorial-2?node-id=0%3A1

**Comment by WilliamShih1234** [comment]
Looks great! This will be your last training before you are ready to start designing parts of websites for our projects! Complete #3 and post it!

**Comment by whichlee** [comment]
apologies for the late action on this one: https://www.figma.com/file/OguMO1kdynxctd7gDbUXcT/act-3?node-id=47%3A7
I'm looking forward to start work with you all!

**Comment by WilliamShih1234** [comment]
No problem. Looks good, you can assign yourself to tasks that are posted in Slack!
