### ISSUE TITLE
samwhich-song training

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/new-ui-designer-training#5]
Complete #1, Share your deliverables as comments below unless otherwise stated

**Comment by samwich-song** [comment]
https://www.figma.com/file/TXIi7E9vCljKQ4sU4t44Vb/Figma-Exercise?node-id=0%3A1

**Comment by toliujiayi** [comment]
Great job! Move on to #2

**Comment by samwich-song** [comment]
https://www.figma.com/file/W4X2XMuTTaKe8sBSMGL76j/Figma-Excercise-2?node-id=0%3A1

**Comment by toliujiayi** [comment]
Great! go on to your last task #3! Keep up the good work!

**Comment by samwich-song** [comment]
https://www.figma.com/file/uckD72yF7V4C2DNf4U6XTg/Figma-Excercise-3?node-id=0%3A1

**Comment by toliujiayi** [comment]
Good work! You are officially ready to move on to real projects!
